service: serverless-lambda-container-otel-js-lib
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-2
  architecture: arm64 # if on MacOS M1, else use default: amd64
  tracing:
    lambda: true
  ecr:
    images:
      example-image:
        path: ./

functions:
  api:
    image:
      name: example-image
    timeout: 10
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://in-otel.codesee.io:443/v1/traces"
      CODESEE_TOKEN: "CodeSee:*** TOKEN HERE" # !! Replace with actual CodeSee token
      SERVICE_NAME: serverless-lambda-container-otel-nodejs-lib-example # !! The service name will shows up on CodeSee Service Map UI
      DEPLOYMENT_ENVIRONMENT: staging # The service environment
      SERVICE_VERSION: 0.1.0 # optional: service version

    events:
      - httpApi:
          path: /
          method: get
