apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
  labels:
    app: k8s-datadog-helm-dual-shipping-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-datadog-helm-dual-shipping-example
  template:
    metadata:
      labels:
        app: k8s-datadog-helm-dual-shipping-example
    spec:
      containers:
      - name: k8s-datadog-helm-dual-shipping-example
        image: k8s-datadog-helm-dual-shipping-example
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: k8s-datadog-helm-dual-shipping-example
  type: LoadBalancer
  ports:
  - protocol: TCP
    # port for exposing the service
    port: 3000
    # port for exposing the pod
    targetPort: 3000
    # port for exposing the node
    nodePort: 30000
