service: serverless-lambda-otel-example
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  tracing:
    lambda: true

functions:
  api:
    handler: index.handler
    timeout: 10
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://in-otel.codesee.io:443/v1/traces"
      CODESEE_TOKEN: "CodeSee:XXX token here"
      SERVICE_NAME: serverless-lambda-otel-example
      DEPLOYMENT_ENVIRONMENT: staging
      SERVICE_VERSION: 0.1.0

    events:
      - httpApi:
          path: /
          method: get

