service: serverless-lambda-otel-js-lib
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  tracing:
    lambda: true

functions:
  api:
    handler: index.handler
    timeout: 10
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://in-otel.codesee.io:443/v1/traces"
      CODESEE_TOKEN: "CodeSee:*** TOKEN HERE" # !! Replace with actual CodeSee token
      SERVICE_NAME: serverless-lambda-otel-nodejs-lib-example # !! The service name will shows up on CodeSee Service Map UI
      DEPLOYMENT_ENVIRONMENT: staging # The service environment
      SERVICE_VERSION: 0.1.0 # optional: service version

    events:
      - httpApi:
          path: /
          method: get

